// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Order struct {
	ID         int64              `json:"id"`
	CustomerID int64              `json:"customer_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Status     pgtype.Text        `json:"status"`
	TotalCents pgtype.Int4        `json:"total_cents"`
}

type OrderItem struct {
	ID         int64 `json:"id"`
	OrderID    int64 `json:"order_id"`
	ProductID  int64 `json:"product_id"`
	Quantity   int32 `json:"quantity"`
	PriceCents int32 `json:"price_cents"`
}

type Product struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	PriceInCents int32              `json:"price_in_cents"`
	Quantity     int32              `json:"quantity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Description  pgtype.Text        `json:"description"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	CategoryID   pgtype.Int8        `json:"category_id"`
	Active       pgtype.Bool        `json:"active"`
	SellerID     pgtype.Int8        `json:"seller_id"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
